hard_tabs = true
use_small_heuristics = "max"
combine_control_expr = false
comment_width = 120
fn_single_line = true
merge_imports = true
max_width = 120
force_multiline_blocks = true
newline_style = "unix"
reorder_impl_items = true
report_todo = "always"
report_fixme = "always"
format_doc_comments = true
wrap_comments = true
color = "always"
unstable_features = true
#license_template_path = ""
normalize_doc_attributes = true
brace_style = "PreferSameLine"